---
# This playbook is used to test the retry logic in a CloudForms state machine
#
# It sets the state result to "retry" for the first 3 runs, then passes successfully

- name: State machine retry testing
  hosts: localhost
  gather_facts: false

  vars:
    - manageiq_validate_certs: false

  roles:
    - syncrou.manageiq-automate

  tasks:
    - debug:
        msg: State retry number {{ workspace.workspace.input.objects.root.ae_state_retries }}

    - name: Set state status to retry
      manageiq_automate:
        workspace: "{{ workspace }}"
        set_retry:
          interval: 600
      when: workspace.workspace.input.objects.root.ae_state_retries|int < 3
